#!/bin/sh

mntpnt="${TOS_MOUNTPOINT:-/mnt/tos}"
isofile="$1"
param2="$2"
grep RedSea < /etc/mtab && fusermount -u ~/iso
echo "waiting for umount..."
while grep RedSea < /etc/mtab; do
  sleep 0.2
done
isoc-mount "$isofile" ~/iso || exit
echo "waiting for mount to come up..."
while ! grep RedSea < /etc/mtab; do
  sleep 0.2
done
shift
case "$param2" in
 --*) destdir="$mntpnt" ;;
 *)
  destdir="$mntpnt/$param2"
  shift
  ;;
esac
mkdir -p "$destdir"
rsync ~/iso/ "$@" --exclude='*.BIN.C' -rv "$destdir" &&
echo "BIN.C files that were NOT copied:" &&
find ~/iso -name '*.BIN.C'
fusermount -u ~/iso
